### PR TITLE
Allow Express to use pithy as view engine

### LINKED ISSUE #8: How to use in expressjs?
How to use in expressjs? I have type "expressjs pithy" in google - no results.

### PR DESCRIPTION
**Pull request by rafis**
resolves #8

### CODE REVIEW

**Comment by derhuerst** [comment]
I don't think an Express view engine belongs into this module. As it is common in the JavaScript ecosystem, you could create a `express-pithy` module and join [others](https://github.com/expressjs/express/wiki#template-engines).

**Comment by derhuerst** [comment]
Also, `require` is synchronous and therefore hurts Node.js in its asynchronous nature.

**Comment by rafis** [comment]
`require` is auto-cachable, and all other view engines do the same: first time view render request recieved, it prepared by view engine and cached somethere. Of course you can pre-cache all views at application startup as you shown in your examples, but that should be done per project and described in `README.md`.

`express-pithy` will require to maintain project which I do not want to do.

I saw another flaws in `pithy`:
- It is allowed to specify multiple ids per tag `html.div('#id1#id2')`, but this should be disallowed as it is disallowed in [HTML spec](http://stackoverflow.com/questions/192048/can-an-html-element-have-multiple-ids).
- It does not supports branching and loops. I need `html.div(null, [function() { if (something) { return html.div(null, 'bla-bla-bla'); } else { return html.div(null, 'yadda-yadda-yadda'); }])`.
- Small optimizations can be done like removing useless function `attrPairs()`.

So perhaps I will create my own library, but not open-source.

I'm currently reading blog of @caolan , it is very cool.

**Comment by derhuerst** [comment]
> `require` is auto-cachable, and all other view engines do the same: first time view render request recieved, it prepared by view engine and cached somethere.

But the template files are being loaded _asynchronously_. `require` loads _synchronously_.

> - It is allowed to specify multiple ids per tag html.div('#id1#id2'), but this should be disallowed as it is disallowed in HTML spec.

You're right. The question is if this should be enforced by pithy.

> - It does not supports branching and loops. I need `html.div(null, [function() { if (something) { return html.div(null, 'bla-bla-bla'); } else { return html.div(null, 'yadda-yadda-yadda'); }])`.

What about this?

``` js
html.div(null, [
    something
        ? html.div(null, 'bla-bla-bla')
        : html.div(null, 'yadda-yadda-yadda')
])
```

> So perhaps I will create my own library, but not open-source.

Why not? It may help other people.

**Pull request closed without merging**
